[packages.archlinux]
regular = [
    "adw-gtk-theme",
    "aquamarine",
    "archlinux-keyring",
    "asciinema",
    "asciinema-agg-bin",
    "ast-grep-bin",
    "base-devel",
    "bat",
    "betterbird-bin",
    "brightnessctl",
    "btop",
    "carla",
    "copyq",
    "cpio",
    "ddcutil-git",
    "devtoolbox",
    "dex",
    "diff-so-fancy",
    "elementary-icon-theme",
    "entr",
    "eza",
    "fd",
    "flatpak",
    "font-manager",
    "fzf",
    "fzy",
    "gearlever",
    "ghostty",
    "git",
    "github-cli",
    "glfw",
    "gnome-disk-utility",
    "gnome-system-monitor",
    "gpa-git",
    "gping",
    "grim",
    "helvum",
    "hyprcursor",
    "hyprgraphics",
    "hypridle",
    "hyprland",
    "hyprland-preview-share-picker-git",
    "hyprland-qt-support",
    "hyprland-guiutils",
    "hyprlang",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "hyprpolkitagent",
    "hyprutils",
    "keepassxc",
    "kitty",
    "lazygit-git",
    "lib32-vulkan-icd-loader",
    "libva",
    "libxml2-legacy",
    "libxnvctrl",
    "linux-headers",
    "linux-zen-headers",
    "luarocks",
    "lutris",
    "mission-center",
    "mpv",
    "mpv-mpris",
    "nautilus",
    "ncdu",
    "neovide",
    "neovim",
    "nodejs",
    "nordvpn-bin",
    "npm",
    "nushell",
    "nwg-look",
    "pamac-aur",
    "pamixer",
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "planify",
    "protonup-qt-bin",
    "ptpython",
    "python-pipx",
    "qt5-wayland",
    "qt5ct",
    "ripgrep",
    "rustup",
    "seahorse",
    "selectdefaultapplication-fork-git",
    "sesh-bin",
    "slurp",
    "steam-native-runtime",
    "steamtinkerlaunch-git",
    "streamlink",
    "swaync",
    "syncthing",
    "syncthing-gtk",
    "tealdeer",
    "telegram-desktop",
    "timg",
    "tmux-git",
    "transmission-gtk",
    "vencord",
    "vlc",
    "vlc-plugins-all",
    "vulkan-icd-loader",
    "vulkan-validation-layers",
    "warehouse-git",
    "waybar",
    "wdisplays",
    "wezterm-git",
    "wikiman",
    "wine",
    "winetricks",
    "wireplumber",
    "wl-clipboard",
    "xcur2png",
    "xdg-desktop-portal-hyprland",
    "yazi-nightly-bin",
    "zen-browser-bin",
    "zoxide",
]
nvidia = [
    "lib32-nvidia-utils",
    "libva-nvidia-driver",
    "nvidia-open-dkms",
    "nvidia-settings",
    "nvidia-utils",
]
